version: 2
jobs:
  build:
   working_directory: ~/repo
   docker:
    - image: circleci/python:3.8
   steps:
     # Obtain the repo from Github
     - checkout
     - run:
        name: install dependencies
        command: |
           sudo pip install pipenv
           pipenv install
     - run:
         name: run tests
         command: |
           pipenv run flake8 --statistics
           pipenv run pytest -v --cov 